# Generated by Django 2.1.4 on 2018-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='avatar',
        ),
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default=1, upload_to='events/'),
            preserve_default=False,
        ),
    ]
