# Generated by Django 2.1.4 on 2018-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181209_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='events.Tag'),
        ),
    ]
