# Generated by Django 2.1.4 on 2018-12-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181215_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_begins',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
