# Generated by Django 2.1.5 on 2019-02-01 19:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_time_begins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_value',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
