# Generated by Django 2.1.5 on 2019-02-01 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190201_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
