# Generated by Django 2.1.5 on 2019-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190201_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_members',
            field=models.IntegerField(default=-1),
        ),
    ]
