# Generated by Django 2.1.4 on 2018-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_tags', to='events.Tag'),
        ),
    ]
