# Generated by Django 2.1.2 on 2018-11-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181116_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
