# Generated by Django 2.1.4 on 2018-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181212_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(to='events.Tag'),
        ),
    ]
