# Generated by Django 2.1.2 on 2018-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181116_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/media/users/a.jpg', upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
