# Generated by Django 2.1.5 on 2019-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_cloud_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cloud_img',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='cloudinary://637921576155489:Fl3bORDQtXlqUHIiUre0engV7QI@son313', upload_to='users/'),
        ),
    ]
