# Generated by Django 2.1.5 on 2019-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190201_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/users/a.jpg', upload_to='loudinary://637921576155489:Fl3bORDQtXlqUHIiUre0engV7QI@son313'),
        ),
    ]
