# Generated by Django 2.1.5 on 2019-02-01 19:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190201_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cloud_img',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
